from os.path import join as j
from os.path import basename
import csv
import json
import collections

configfile: "config/config.json"

##############################################################################
# Folders
###############################################################################
MAG_RAW = config["raw_data_path"]
MAG_PROC = config["proc_data_path"]

##############################################################################
# Files
###############################################################################

MAG_MAIN_FILES = j(MAG_RAW, "mag", "{file}.txt")
MAG_ADV_FILES = j(MAG_RAW, "advanced", "{file}.txt")

MAG_MAIN_FILES_PROC = j(MAG_PROC, "main", "{file}.jsonl")
MAG_ADV_FILES_PROC = j(MAG_PROC, "advanced", "{file}.jsonl")

MAG_SCHEMAS = "schemas/{file}_schema.json"

##############################################################################
# Parameters
###############################################################################
main_files = ["Papers", "Authors", "Affiliations", "Journals",
              "PaperUrls", "PaperReferences", "PaperAuthorAffiliations"]

adv_files = ["PaperMeSH", "FieldsOfStudy", "FieldOfStudyChildren", "PaperFieldsOfStudy"]

##############################################################################
# Target
###############################################################################
rule all:
    input:
        expand(MAG_MAIN_FILES, file = main_files),
        expand(MAG_ADV_FILES, file = adv_files),
        expand(MAG_MAIN_FILES_PROC, file = main_files),
        expand(MAG_ADV_FILES_PROC, file = adv_files),

include: "rules/download.smk"
include: "rules/process.smk"
